name: Checks, Build, Publish, Deploy

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  
  checks:
    runs-on: ubuntu-latest
    env:
      APP_FOLDER: ApiFake

    steps:
      - uses: actions/checkout@v2
      
      - name: Setup .NET Core SDK '5.0.x'
        uses: actions/setup-dotnet@v1.7.2
        with:
          dotnet-version: '5.0.x'

      - name: Install dependencies
        run: |
          cd ${{ env.APP_FOLDER }} 
          dotnet restore

      - name: Build
        run: dotnet build --configuration Release --no-restore

      - name: Test
        run: dotnet test --no-restore --verbosity normal

  build:
    name: Build Image and Push to ACR
    needs: [checks]
    runs-on: ubuntu-latest
    env:
      APP_FOLDER: ApiFake

    steps:
    - uses: actions/checkout@v2

    - name: Docker Login
      uses: Azure/docker-login@v1
      with:
        login-server: ${{ secrets.DOCKER_REGISTRY }}
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and Push in Azure ACR
      run: |
        docker build . --file ./${{ env.APP_FOLDER }}/Dockerfile --tag ${{ secrets.IMAGE_NAME }}:$GITHUB_RUN_NUMBER
        docker tag ${{ secrets.IMAGE_NAME }}:$GITHUB_RUN_NUMBER ${{ secrets.IMAGE_NAME }}:latest
        docker push ${{ secrets.IMAGE_NAME }}:$GITHUB_RUN_NUMBER
        docker push ${{ secrets.IMAGE_NAME }}
  
  deploy:
    name: Deploying Az Web App
    runs-on: ubuntu-latest
    needs: [ build ]
    env:
      WEB_APP: webappexpertsclub03example 

    steps:

      - name: Azure login
        uses: Azure/login@v1.1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Web App Deployment
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.WEB_APP }}
          images: ${{ secrets.IMAGE_NAME }}:latest
          slot-name: staging
